### ISSUE TITLE
Add more meta data to bus JSON

### ISSUE THREAD

**Issue by slowe** [open-innovations/bus-tracking#1]
The individual JSON files now have `agency_name` in a `meta` field. It'd be useful to also include:

  - [x] `service` - the service number e.g. `33`
  - [x] `id` - unique for the country and preferably match that used by https://bustimes.org/services/33-leeds-otley e.g. `33-leeds-otley`
  - [x] `name` - a more descriptive version of the route e.g. `Leeds City Bus Station - Ilkley, Guiseley - Otley Bus Station`.
  - [x] `agency_noc` - the national operator code e.g. `FLDS`

The keys don't have to have these exact names - use whatever is more correct.
